use crate::core::aircraft::Side;

#[derive(Debug, Clone, Copy, PartialEq)]
pub struct AircraftSpec {
    pub model: &'static str,
    pub max_speed_knots: f32,
    pub cruise_speed_knots: f32,
    pub fuel_capacity_kg: f32,
    pub fuel_burn_kg_per_s: f32,
    pub radar_range_km: f32,
    pub radar_fov_deg: f32,
    pub empty_weight_kg: f32,
    pub rcs_frontal: f32,
    pub rcs_side: f32,
    pub is_stealth: bool,
}

pub const SPECS: &[AircraftSpec] = &[
    AircraftSpec {
        model: "F-15C Eagle",
        max_speed_knots: 1450.0,
        cruise_speed_knots: 560.0,
        fuel_capacity_kg: 6100.0,
        fuel_burn_kg_per_s: 0.15,
        radar_range_km: 160.0,
        radar_fov_deg: 120.0,
        empty_weight_kg: 12700.0,
        rcs_frontal: 5.0,
        rcs_side: 10.0,
        is_stealth: false,
    },
    AircraftSpec {
        model: "Su-27 Flanker",
        max_speed_knots: 1350.0,
        cruise_speed_knots: 540.0,
        fuel_capacity_kg: 9400.0,
        fuel_burn_kg_per_s: 0.18,
        radar_range_km: 150.0,
        radar_fov_deg: 130.0,
        empty_weight_kg: 16380.0,
        rcs_frontal: 10.0,
        rcs_side: 15.0,
        is_stealth: false,
    },
    AircraftSpec {
        model: "F-16C Viper",
        max_speed_knots: 1150.0,
        cruise_speed_knots: 520.0,
        fuel_capacity_kg: 3200.0,
        fuel_burn_kg_per_s: 0.12,
        radar_range_km: 110.0,
        radar_fov_deg: 120.0,
        empty_weight_kg: 8570.0,
        rcs_frontal: 1.2,
        rcs_side: 3.5,
        is_stealth: false,
    },
    AircraftSpec {
        model: "F-22 Raptor",
        max_speed_knots: 1500.0,
        cruise_speed_knots: 650.0,
        fuel_capacity_kg: 8200.0,
        fuel_burn_kg_per_s: 0.14,
        radar_range_km: 210.0,
        radar_fov_deg: 140.0,
        empty_weight_kg: 19700.0,
        rcs_frontal: 0.0001,
        rcs_side: 0.005,
        is_stealth: true,
    },
    AircraftSpec {
        model: "Su-57 Felon",
        max_speed_knots: 1350.0,
        cruise_speed_knots: 600.0,
        fuel_capacity_kg: 10300.0,
        fuel_burn_kg_per_s: 0.17,
        radar_range_km: 180.0,
        radar_fov_deg: 150.0,
        empty_weight_kg: 18000.0,
        rcs_frontal: 0.1,
        rcs_side: 0.5,
        is_stealth: true,
    },
    AircraftSpec {
        model: "A-10 Warthog",
        max_speed_knots: 370.0,
        cruise_speed_knots: 300.0,
        fuel_capacity_kg: 4850.0,
        fuel_burn_kg_per_s: 0.08,
        radar_range_km: 30.0,
        radar_fov_deg: 60.0,
        empty_weight_kg: 11300.0,
        rcs_frontal: 5.0,
        rcs_side: 12.0,
        is_stealth: false,
    },
    AircraftSpec {
        model: "B-2 Spirit",
        max_speed_knots: 550.0,
        cruise_speed_knots: 480.0,
        fuel_capacity_kg: 75000.0,
        fuel_burn_kg_per_s: 0.25,
        radar_range_km: 150.0,
        radar_fov_deg: 120.0,
        empty_weight_kg: 71700.0,
        rcs_frontal: 0.0001,
        rcs_side: 0.0005,
        is_stealth: true,
    },
    AircraftSpec {
        model: "E-3 Sentry",
        max_speed_knots: 460.0,
        cruise_speed_knots: 400.0,
        fuel_capacity_kg: 90000.0,
        fuel_burn_kg_per_s: 0.35,
        radar_range_km: 600.0,
        radar_fov_deg: 360.0,
        empty_weight_kg: 73500.0,
        rcs_frontal: 120.0,
        rcs_side: 200.0,
        is_stealth: false,
    },
];

pub fn get_random_spec(_side: Side) -> AircraftSpec {
    use rand::seq::SliceRandom;
    let mut rng = rand::thread_rng();
    *SPECS.choose(&mut rng).unwrap()
}
